language: php
sudo: required
before_install:
  - sudo docker pull hightman/xunsearch
  - docker run --name xunsearch -d \
  -p 8383:8383 -p 8384:8384 \
  -v /var/xunsearch/data:/usr/local/xunsearch/data \
  hightman/xunsearch:latest
php:
  - 7.1
before_script:
  - composer install

script:
  - vendor/bin/phpunit tests/SearchTest